{% set version = "3.0.3" %}

package:
  name: pyviz_comms
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyviz_comms/pyviz_comms-{{ version }}.tar.gz
  sha256: fde4a017c2213ecee63a9a6741431c845e42a5c7b1588e4a7ba2e4370c583728

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - param
    - pip
    - jupyter-packaging >=0.7.9,<0.8
    - jupyterlab >=4.0,<5
    - notebook
    - hatchling
    - hatch-nodejs-version
    - hatch-jupyter-builder
  run:
    - python >={{ python_min }}
    - param
  run_constrained:
    - jupyterlab >=4.0,<5

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyviz_comms

about:
  home: https://www.holoviz.org
  summary: Bidirectional communication for PyViz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - maximlt
