{% set version = "0.6.0" %}

package:
  name: pyviz_comms
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyviz_comms/pyviz_comms-{{ version }}.tar.gz
  sha256: be3cd85b1c6cf842d7cac7db0428bf015d16d0ea33e0767d602061cf6964a51a

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

  
requirements:
  host:
    - python
    - param
    - pip
  run:
    - python
    - param

test:
  imports:
    - pyviz_comms

about:
  home: https://www.pyviz.org
  summary: Bidirectional communication for PyViz
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
