{% set version = "0.7.1" %}

package:
  name: pyviz_comms
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyviz_comms/pyviz_comms-{{ version }}.tar.gz
  sha256: 5854e3b2145f1827520a61331a5a54a915f03d7c97e0ff9177000f659196ab10

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

  
requirements:
  host:
    - python
    - param
    - pip
  run:
    - python
    - param

test:
  imports:
    - pyviz_comms

about:
  home: https://www.pyviz.org
  summary: Bidirectional communication for PyViz
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
